### ISSUE TITLE
Comment (method and class)

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/mre#10]
[`(?#...)`](https://docs.python.org/3.7/library/re.html#index-19)

- [x] Create `comment` method, which adds comments to regex.
- [x] Create `Comment` class, inheriting from Group.

Method behavior example:
```py
from mre import Regex, Set

# All digits
digits = Set(Regex("0-9"))
# CEP regex
rgx_cep = Regex(
    digits.quantifier(5),
    Regex("-").quantifier(0, 1),
    digits.quantifier(3),
).comment('Get zip code Brazil on input')

# Output: [0-9]{5}-?[0-9]{3}(?#Get zip code Brazil on input)
# Regex without comment: [0-9]{5}-?[0-9]{3}
```

Class behavior example:
```py
from mre import Regex, Set, Comment

# All digits
digits = Set(Regex("0-9"))
# CEP comment
cep_comment = Comment('Get zip code Brazil on input')
# CEP regex
rgx_cep = Regex(
    digits.quantifier(5),
    Regex("-").quantifier(0, 1),
    digits.quantifier(3),
    cep_comment
)

# Output: [0-9]{5}-?[0-9]{3}(?#Get zip code Brazil on input)
# Regex without comment: [0-9]{5}-?[0-9]{3}
```

![comment](https://user-images.githubusercontent.com/10817238/65914263-7b593c00-e3a7-11e9-8582-c579cac63c0d.png)

**Comment by kauziishere** [comment]
Okay, I can get on this task.

**Comment by kauziishere** [comment]
I have one doubt regarding this. In the example which you have stated for the comment method, you have the ".comment" which returns the Regex object which seems to destroy the purpose of class it's similar to Python syntax but just wanted to verify it.

**Comment by alvarofpp** [comment]
@kauziishere 
The intention is to actually return a new Regex object with its `self.rgx` value modified with the comment you entered. If you prefer, you can have another internal attribute for saving comments and such a serious attribute called when showing the total of regular expressions, as in `print()` or `.get()`.

**Comment by kauziishere** [comment]
Got it creating a pull request
